/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDataAirtimeRouteImport } from './routes/_authenticated/data-airtime'
import { Route as AuthenticatedDisputesRouteImport } from './routes/_authenticated/disputes'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AdAdIdRouteImport } from './routes/ad.$adId'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as UserUsernameRouteImport } from './routes/user.$username'
import { Route as AuthenticatedAdsIndexRouteImport } from './routes/_authenticated/ads/index'
import { Route as AuthenticatedAdsNewRouteImport } from './routes/_authenticated/ads/new'
import { Route as AuthenticatedCheckoutAdIdRouteImport } from './routes/_authenticated/checkout.$adId'
import { Route as AuthenticatedDisputeDisputeIdRouteImport } from './routes/_authenticated/dispute.$disputeId'
import { Route as AuthenticatedAdsAdIdEditRouteImport } from './routes/_authenticated/ads/$adId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataAirtimeRoute =
  AuthenticatedDataAirtimeRouteImport.update({
    id: '/data-airtime',
    path: '/data-airtime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisputesRoute = AuthenticatedDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdAdIdRoute = AdAdIdRouteImport.update({
  id: '/ad/$adId',
  path: '/ad/$adId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdsIndexRoute = AuthenticatedAdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdsNewRoute = AuthenticatedAdsNewRouteImport.update({
  id: '/ads/new',
  path: '/ads/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutAdIdRoute =
  AuthenticatedCheckoutAdIdRouteImport.update({
    id: '/checkout/$adId',
    path: '/checkout/$adId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisputeDisputeIdRoute =
  AuthenticatedDisputeDisputeIdRouteImport.update({
    id: '/dispute/$disputeId',
    path: '/dispute/$disputeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdsAdIdEditRoute =
  AuthenticatedAdsAdIdEditRouteImport.update({
    id: '/ads/$adId/edit',
    path: '/ads/$adId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-airtime': typeof AuthenticatedDataAirtimeRoute
  '/disputes': typeof AuthenticatedDisputesRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/ad/$adId': typeof AdAdIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/ads/new': typeof AuthenticatedAdsNewRoute
  '/checkout/$adId': typeof AuthenticatedCheckoutAdIdRoute
  '/dispute/$disputeId': typeof AuthenticatedDisputeDisputeIdRoute
  '/ads/': typeof AuthenticatedAdsIndexRoute
  '/ads/$adId/edit': typeof AuthenticatedAdsAdIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-airtime': typeof AuthenticatedDataAirtimeRoute
  '/disputes': typeof AuthenticatedDisputesRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/ad/$adId': typeof AdAdIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/ads/new': typeof AuthenticatedAdsNewRoute
  '/checkout/$adId': typeof AuthenticatedCheckoutAdIdRoute
  '/dispute/$disputeId': typeof AuthenticatedDisputeDisputeIdRoute
  '/ads': typeof AuthenticatedAdsIndexRoute
  '/ads/$adId/edit': typeof AuthenticatedAdsAdIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-airtime': typeof AuthenticatedDataAirtimeRoute
  '/_authenticated/disputes': typeof AuthenticatedDisputesRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/ad/$adId': typeof AdAdIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/_authenticated/ads/new': typeof AuthenticatedAdsNewRoute
  '/_authenticated/checkout/$adId': typeof AuthenticatedCheckoutAdIdRoute
  '/_authenticated/dispute/$disputeId': typeof AuthenticatedDisputeDisputeIdRoute
  '/_authenticated/ads/': typeof AuthenticatedAdsIndexRoute
  '/_authenticated/ads/$adId/edit': typeof AuthenticatedAdsAdIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email'
    | '/join'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/checkin'
    | '/coupons'
    | '/dashboard'
    | '/data-airtime'
    | '/disputes'
    | '/friends'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/sell'
    | '/settings'
    | '/support'
    | '/wallet'
    | '/ad/$adId'
    | '/order/$orderId'
    | '/user/$username'
    | '/ads/new'
    | '/checkout/$adId'
    | '/dispute/$disputeId'
    | '/ads/'
    | '/ads/$adId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/join'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/checkin'
    | '/coupons'
    | '/dashboard'
    | '/data-airtime'
    | '/disputes'
    | '/friends'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/sell'
    | '/settings'
    | '/support'
    | '/wallet'
    | '/ad/$adId'
    | '/order/$orderId'
    | '/user/$username'
    | '/ads/new'
    | '/checkout/$adId'
    | '/dispute/$disputeId'
    | '/ads'
    | '/ads/$adId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/check-email'
    | '/join'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/checkin'
    | '/_authenticated/coupons'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-airtime'
    | '/_authenticated/disputes'
    | '/_authenticated/friends'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/sell'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/wallet'
    | '/ad/$adId'
    | '/order/$orderId'
    | '/user/$username'
    | '/_authenticated/ads/new'
    | '/_authenticated/checkout/$adId'
    | '/_authenticated/dispute/$disputeId'
    | '/_authenticated/ads/'
    | '/_authenticated/ads/$adId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AdAdIdRoute: typeof AdAdIdRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  UserUsernameRoute: typeof UserUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-airtime': {
      id: '/_authenticated/data-airtime'
      path: '/data-airtime'
      fullPath: '/data-airtime'
      preLoaderRoute: typeof AuthenticatedDataAirtimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disputes': {
      id: '/_authenticated/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedDisputesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ad/$adId': {
      id: '/ad/$adId'
      path: '/ad/$adId'
      fullPath: '/ad/$adId'
      preLoaderRoute: typeof AdAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ads/': {
      id: '/_authenticated/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AuthenticatedAdsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads/new': {
      id: '/_authenticated/ads/new'
      path: '/ads/new'
      fullPath: '/ads/new'
      preLoaderRoute: typeof AuthenticatedAdsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$adId': {
      id: '/_authenticated/checkout/$adId'
      path: '/checkout/$adId'
      fullPath: '/checkout/$adId'
      preLoaderRoute: typeof AuthenticatedCheckoutAdIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispute/$disputeId': {
      id: '/_authenticated/dispute/$disputeId'
      path: '/dispute/$disputeId'
      fullPath: '/dispute/$disputeId'
      preLoaderRoute: typeof AuthenticatedDisputeDisputeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads/$adId/edit': {
      id: '/_authenticated/ads/$adId/edit'
      path: '/ads/$adId/edit'
      fullPath: '/ads/$adId/edit'
      preLoaderRoute: typeof AuthenticatedAdsAdIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataAirtimeRoute: typeof AuthenticatedDataAirtimeRoute
  AuthenticatedDisputesRoute: typeof AuthenticatedDisputesRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedAdsNewRoute: typeof AuthenticatedAdsNewRoute
  AuthenticatedCheckoutAdIdRoute: typeof AuthenticatedCheckoutAdIdRoute
  AuthenticatedDisputeDisputeIdRoute: typeof AuthenticatedDisputeDisputeIdRoute
  AuthenticatedAdsIndexRoute: typeof AuthenticatedAdsIndexRoute
  AuthenticatedAdsAdIdEditRoute: typeof AuthenticatedAdsAdIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataAirtimeRoute: AuthenticatedDataAirtimeRoute,
  AuthenticatedDisputesRoute: AuthenticatedDisputesRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedAdsNewRoute: AuthenticatedAdsNewRoute,
  AuthenticatedCheckoutAdIdRoute: AuthenticatedCheckoutAdIdRoute,
  AuthenticatedDisputeDisputeIdRoute: AuthenticatedDisputeDisputeIdRoute,
  AuthenticatedAdsIndexRoute: AuthenticatedAdsIndexRoute,
  AuthenticatedAdsAdIdEditRoute: AuthenticatedAdsAdIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AdAdIdRoute: AdAdIdRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  UserUsernameRoute: UserUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
